{{- if .Values.webhook.rbac.create -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "db-operator.webhook.name" . }}
  labels:
    {{- include "db-operator.webhook.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kinda.rocks
  resources:
  - databases
  - dbinstances
  - dbusers
  - dbbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end -}}
