{{- if .Values.webhook.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "db-operator.webhook.serviceAccountName" . }}
  labels:
    {{- include "db-operator.webhook.labels" $ | nindent 4 }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 2 }}
{{- end }}
{{- end -}}
